apiVersion: apps/v1
kind: Deployment
metadata:
  name: rca-agent
  labels:
    app: rca-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rca-agent
  template:
    metadata:
      labels:
        app: rca-agent
    spec:
      serviceAccountName: rca-agent-sa
      containers:
      - name: rca-agent
        image: quay.io/rh-ee-shesaxen/rca-agent:poc19
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: rca-agent
spec:
  selector:
    app: rca-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
